### ISSUE TITLE
API function name typo

### ISSUE THREAD

**Issue by proto3** [jbuckmccready/CavalierContours#25]
https://github.com/jbuckmccready/CavalierContours/blob/8bd76c95bfcc5e73007b50732fbeb8c52ef4f024/c_api_include/cavaliercontours.h#L131

**cavc_parallel_offet** instead of **cavc_parallel_offset**

**Comment by jbuckmccready** [comment]
Good catch, thanks for making the issue. Renamed in commit https://github.com/jbuckmccready/CavalierContours/commit/9e845ebaaa27e006693a3e7cfca2f1cf36a950f5
