### ISSUE TITLE
ASSERT -> v1 must not be ontop of v2

### ISSUE THREAD

**Issue by kadircanik** [jbuckmccready/CavalierContours#37]
Following polyline is giving assert;

`Path P;`
`P.addVertex(30.123475382979791, -17.00000, 0.00000);`
`P.addVertex(42.000000000000000, -17.00000, 0.00000);`
`P.addVertex(42.000000000000000,  17.00000, 0.00000);`
`P.addVertex(30.123475382979798,  17.00000, -0.093311550024413187);`
`P.addVertex(30.500000000000000,  15.00000,  0.00000);`
`P.addVertex(30.500000000000000, -15.00000, -0.093311550024413409);`
`parallelOffset(P, -2.0);`

**Comment by jbuckmccready** [comment]
Interesting specific edge case you found, thanks for reporting the issue. I committed a fix: https://github.com/jbuckmccready/CavalierContours/commit/ad10845e7d65e7efc150bd521100f537f4e555bb

**Comment by kadircanik** [comment]
Thank you
