### ISSUE TITLE
Support polyline with multiple offsets

### ISSUE THREAD

**Issue by WindingWinter** [jbuckmccready/CavalierContours#47]
Currently only uniform offset can be done throughout all the vertexes on the polylines.

Is there any plan to support variable offsets? Something like [NetTopologySuite VariableBuffer](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Operation.Buffer.VariableBuffer.html#NetTopologySuite_Operation_Buffer_VariableBuffer__ctor_NetTopologySuite_Geometries_Geometry_System_Double___).

**Comment by jbuckmccready** [comment]
Closing this issue in favor of the one in the Rust project: https://github.com/jbuckmccready/cavalier_contours/issues/19
