### ISSUE TITLE
std::unique_ptr is defined in header <memory>

### ISSUE THREAD

**Issue by Trotew** [jbuckmccready/CavalierContours#6]
It will cause some small problems in GCC compile environment.

https://en.cppreference.com/w/cpp/memory/unique_ptr

**Comment by Trotew** [comment]
Some header files using std::unique_ptr don't include <memory>

**Comment by jbuckmccready** [comment]
Thanks for the report, I normally build with with GCC but I hadn't since I made some changes recently. I pushed a fix (https://github.com/jbuckmccready/CavalierContours/commit/e4b2b2e98000ada0c6863bbce8ed53bad9ccde67).
