### ISSUE TITLE
generate offset contour of a line segment

### ISSUE THREAD

**Issue by kalluwa** [jbuckmccready/CavalierContours#60]
i tested a line segment in rust web demo, it works fine:
![image](https://user-images.githubusercontent.com/9412335/230920571-c60fa581-b9a6-43e1-a748-62fd9866ad42.png)

but this cpp demo failed:
![image](https://user-images.githubusercontent.com/9412335/230921724-34f36d4a-048a-4a2a-b754-31c8d40dd061.png)

after adding a another point,it can produce right result:
![image](https://user-images.githubusercontent.com/9412335/230921220-14bf532f-9b8e-4f73-beca-2f69b15cf7b3.png)

could this be normal behavior?

**Comment by jbuckmccready** [comment]
This is likely a bug in the C++ code (since there are many that have been fixed in Rust and not back ported), I am not maintaining the C++ code, see this pinned issue: https://github.com/jbuckmccready/CavalierContours/issues/41

**Comment by kalluwa** [comment]
thanks for your reply. 
it should not be a difficult problem(i guess), i'll debug it later
