### ISSUE TITLE
Whether the interpolation coordinates of the arc are provided

### ISSUE THREAD

**Issue by whucj** [jbuckmccready/CavalierContours#8]
I get the "bulge" by parallelOffset method .
I want to transform the arc to polyline.
Whether the interpolation coordinates of the arc are provided？
Thanks

**Comment by jbuckmccready** [comment]
@whucj If I understand correctly you're asking how to convert the polyline with arcs to a polyline with no arcs (arcs approximated as lines)? You can use the `convertArcsToLines` function in `polyline.hpp`, function is here in the code: https://github.com/jbuckmccready/CavalierContours/blob/master/include/cavc/polyline.hpp#L387

If you're looking to convert an existing arc that is not defined by a bulge to an arc that is a defined by a bulge then you can compute the bulge from the arc sweep angle. There are a number of ways to get the bulge depending on how your arc is defined, see this reference for math and diagrams: http://www.lee-mac.com/bulgeconversion.html

**Comment by whucj** [comment]
thanks
